services:
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    expose:
      - "80"
    container_name: mimo-web
    env_file:
      - ./frontend/.env
    networks:
      - frontend_backend_network
    volumes:  
      - /usr/share/nginx/html:/usr/share/nginx/html

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    expose:
      - "8080"
    container_name: mimo-server
    env_file:
      - ./backend/.env
    networks:
      - frontend_backend_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    container_name: mimo-nginx
    networks:
      - frontend_backend_network
    volumes:
      - /home/ubuntu/A504/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  frontend_backend_network:
    name: frontend_backend_network
    driver: bridge
