services:
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"
    container_name: mimo-web
    env_file:
      - ./frontend/.env
    networks:
      - frontend_backend_network

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    container_name: mimo-server
    env_file:
      - ./backend/.env
    networks:
      - frontend_backend_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    container_name: mimo-nginx    
    networks:
      - frontend_backend_network
    depends_on:
      - web
      - server
    volumes:
      - /home/ubuntu/A504/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  frontend_backend_network:
    name: frontend_backend_network
    driver: bridge
