services:
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"
    container_name: mimo-web
    env_file:
      - ./frontend/.env
    networks:
      - frontend_backend_network

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    container_name: mimo-server
    env_file:
      - ./backend/.env
    networks:
      - frontend_backend_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    container_name: mimo-nginx
    networks:
      - frontend_backend_network
    volumes:
      - /home/ubuntu/A504/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  frontend_backend_network:
    name: frontend_backend_network
    driver: bridge
