services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - mimo-web
      - mimo-server
      - certbot  # certbot이 실행된 후 nginx 실행

  mimo-web:
    build: ./mimo-web
    container_name: mimo-web
    restart: always

  mimo-server:
    build: ./mimo-server
    container_name: mimo-server
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'if [ ! -f /etc/letsencrypt/live/i12a504.p.ssafy.io/fullchain.pem ]; then certbot certonly --webroot -w /var/www/certbot --email your-email@example.com -d i12a504.p.ssafy.io --agree-tos --no-eff-email --force-renewal; fi; trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done'"
