services:
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"
    container_name: mimo-web
    env_file:
      - ./frontend/.env
    networks:
      - frontend_backend_network

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    container_name: mimo-server
    env_file:
      - ./backend/.env
    networks:
      - frontend_backend_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    container_name: mimo-nginx    
    networks:
      - frontend_backend_network
    depends_on:
      certbot:
        condition: service_completed_successfully
    volumes:
      - /home/ubuntu/A504/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/A504/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/A504/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/A504/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/A504/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c '
      if [ ! -f /etc/letsencrypt/live/i12a504.p.ssafy.io/fullchain.pem ]; then
        certbot certonly --webroot -w /var/www/certbot --email your-email@example.com -d i12a504.p.ssafy.io --agree-tos --no-eff-email --force-renewal;
      fi;
      exit 0;
      '

networks:
  frontend_backend_network:
    name: frontend_backend_network
    driver: bridge
