services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: mimo-nginx
    networks:
      - frontend_backend_network
    depends_on:
      - certbot  # depends_on을 올바르게 수정
    volumes:
      - /home/ubuntu/A504/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/A504/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/A504/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/A504/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/A504/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c '
        if [ ! -f /etc/letsencrypt/live/i12a504.p.ssafy.io/fullchain.pem ]; then
          certbot certonly --webroot -w /var/www/certbot -d i12a504.p.ssafy.io --email pkb1998@naver.com --agree-tos --no-eff-email --force-renewal --redirect;
        else
          certbot renew --quiet --webroot -w /var/www/certbot;
        fi;
      '

networks:
  frontend_backend_network:
    name: frontend_backend_network
    driver: bridge
