spring:
  application:
    name: backend

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    token-uri: ${GOOGLE_TOKEN_URI}
    resource-uri: ${GOOGLE_RESOURCE_URI}
    scope:
      - email
      - profile
