spring:
  application:
    name: backend

  auth:
    jwt:
      secret-key: ${SECRET_KEY}
      access-token-expiry: ${ACCESS_TOKEN_EXPIRY}
      refresh-token-expiry: ${REFRESH_TOKEN_EXPIRY}

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_URL}/oauth2?socketTimeout=2000
    hikari:
      connection-timeout: 3000

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQLDialect

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    token-uri: ${GOOGLE_TOKEN_URI}
    resource-uri: ${GOOGLE_RESOURCE_URI}
    scope:
      - email
      - profile
      - openid
